title: "Subset.tv Blog"
email: hello@subset.tv
description: >-
  Welcome to the official blog of Subset.tv. We're here to help you rediscover 
  your favorite shows, one perfect episode collection at a time. Beyond the binge.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Subset.tv specific settings
subset:
  tagline: "Beyond the Binge"
  hero_description: "Welcome to the official blog of Subset.tv. We're here to help you rediscover your favorite shows, one perfect episode collection at a time."
  
# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  spotlights:
    output: true
    permalink: /:collection/:name/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
